# Generated by Django 3.1.6 on 2021-02-15 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticias",
            name="postador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="matricula",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="matricula",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.curso"
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="certificado",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Alunos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificado",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.curso"
            ),
        ),
        migrations.AddField(
            model_name="certificado",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Professor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
