# Generated by Django 3.1.6 on 2021-02-16 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_auto_20210216_1324"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="certificate title",
                        max_length=100,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="certificate description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="file with the certificate",
                        upload_to="%Y/%m/%d/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="certificate creation date",
                        verbose_name="Created",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="course name", max_length=200, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Course description", verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        help_text="Course cover image",
                        upload_to="%Y/%m/%d/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="Course creation date",
                        verbose_name="Created in",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        help_text="course theme", max_length=30, verbose_name="Theme"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Course teacher",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        help_text="Event start date", verbose_name="Starts in"
                    ),
                ),
                (
                    "ends_in",
                    models.DateTimeField(
                        help_text="End date of the event", verbose_name="Ends in"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="title of the event",
                        max_length=100,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Event description or summary",
                        verbose_name="Description",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="creation date of the event in the system",
                        verbose_name="Created",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="New",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="title of the news",
                        max_length=100,
                        verbose_name="Title",
                    ),
                ),
                (
                    "abstract",
                    models.TextField(help_text="news summary", verbose_name="Abstract"),
                ),
                (
                    "content",
                    models.TextField(help_text="news content", verbose_name="Content"),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        help_text="news cover image",
                        upload_to="%Y/%m/%d/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "posted_in",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="news posting date",
                        verbose_name="Posted in",
                    ),
                ),
                (
                    "poster",
                    models.ForeignKey(
                        help_text="news editor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="registration creation date",
                        verbose_name="Created in",
                    ),
                ),
                (
                    "finished",
                    models.DateTimeField(
                        blank=True,
                        help_text="end date of the student's enrollment course",
                        null=True,
                        verbose_name="Finished",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="enrollment course",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="enrollment student",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="certificado",
            name="course",
        ),
        migrations.RemoveField(
            model_name="certificado",
            name="student",
        ),
        migrations.RemoveField(
            model_name="certificado",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="curso",
            name="teacher",
        ),
        migrations.DeleteModel(
            name="Evento",
        ),
        migrations.RemoveField(
            model_name="matricula",
            name="course",
        ),
        migrations.RemoveField(
            model_name="matricula",
            name="student",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="poster",
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.FileField(
                help_text="Image url and path", upload_to="", verbose_name="Imagem"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(
                blank=True, help_text="Image name", max_length=100, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="upload_in",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="image upload date",
                verbose_name="Upload in",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(help_text="post content", verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.FileField(
                blank=True,
                help_text="post cover image",
                upload_to="%Y/%m/%d/",
                verbose_name="Imagem",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="posted_in",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="post publication date",
                verbose_name="Posted in",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="poster",
            field=models.ForeignKey(
                help_text="post editor",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                help_text="post title", max_length=100, verbose_name="Title"
            ),
        ),
        migrations.DeleteModel(
            name="Certificado",
        ),
        migrations.DeleteModel(
            name="Curso",
        ),
        migrations.DeleteModel(
            name="Matricula",
        ),
        migrations.DeleteModel(
            name="Noticia",
        ),
        migrations.AddField(
            model_name="certificate",
            name="course",
            field=models.ForeignKey(
                help_text="certificate course",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.course",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="referring_registration",
            field=models.ForeignKey(
                blank=True,
                help_text="Enrollment contained in the certificate",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.registration",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="student",
            field=models.ForeignKey(
                help_text="student who will receive the certificate",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Alunos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="teacher",
            field=models.ForeignKey(
                help_text="teacher responsible for sending the certificate to the system / issuing the certificate",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Professor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
