# Generated by Django 3.1.6 on 2021-03-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210218_2111"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
