# Generated by Django 3.1.6 on 2021-02-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20210215_1612"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticias",
            name="imagem",
        ),
        migrations.AddField(
            model_name="noticias",
            name="arquivo",
            field=models.FileField(blank=True, upload_to="%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="certificado",
            name="arquivo",
            field=models.FileField(blank=True, upload_to="%Y/%m/%d/"),
        ),
    ]
