# Generated by Django 3.1.6 on 2021-02-17 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20210217_1101"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="course type name",
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="Course Type creation date",
                        verbose_name="Created in",
                    ),
                ),
            ],
        ),
    ]
