# Generated by Django 3.1.6 on 2021-02-15 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_auto_20210215_1832"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comeca_em", models.DateTimeField()),
                ("termina_em", models.DateTimeField()),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "criado_em",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="noticias",
            old_name="arquivo",
            new_name="imagem",
        ),
        migrations.AlterField(
            model_name="certificado",
            name="titulo",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="noticias",
            name="titulo",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("conteudo", models.TextField()),
                ("imagem", models.FileField(blank=True, upload_to="%Y/%m/%d/")),
                (
                    "postado_em",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "postador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
