# Generated by Django 3.1.6 on 2021-02-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_coursetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetype",
            name="image",
            field=models.FileField(
                blank=True,
                help_text="Course Type cover image",
                upload_to="%Y/%m/%d/",
                verbose_name="Imagem",
            ),
        ),
    ]
