# Generated by Django 3.1.6 on 2021-02-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210215_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/'),
        ),
    ]
