# Generated by Django 3.1.6 on 2021-03-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210302_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(help_text='post cover image', upload_to='%Y/%m/%d/', verbose_name='Imagem'),
        ),
    ]
