# Generated by Django 3.1.6 on 2021-03-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20210302_2039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new",
            name="processed_abstract",
            field=models.TextField(
                blank=True,
                default="",
                help_text="news processed summary",
                verbose_name="Abstract",
            ),
        ),
        migrations.AlterField(
            model_name="new",
            name="processed_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="news processed content",
                verbose_name="Processed Content",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="processed_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="post processed content",
                verbose_name="Processed Content",
            ),
        ),
    ]
