# Generated by Django 3.1.7 on 2021-03-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20210303_1345"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new",
            name="processed_abstract",
            field=models.TextField(
                blank=True,
                default="",
                help_text="news processed summary",
                verbose_name="processed Abstract",
            ),
        ),
    ]
