# Generated by Django 3.1.7 on 2021-03-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20210303_2014"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="regiao",
            field=models.CharField(
                choices=[("A", "Nacional"), ("B", "Internacional")],
                default="A",
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("A", "Olimpiada"),
                    ("B", "Evento"),
                    ("C", "Feira de ciências"),
                ],
                default="A",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
