# Generated by Django 3.1.7 on 2021-04-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20210308_1351"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="post cover image",
                upload_to="%Y/%m/%d/",
                verbose_name="Imagem",
            ),
        ),
    ]
