# Generated by Django 3.1.7 on 2021-04-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_image_uploader"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prova", models.FileField(blank=True, upload_to="desafio/%Y/%m/%d/")),
                (
                    "gabarito",
                    models.FileField(blank=True, upload_to="desafio/%Y/%m/%d/"),
                ),
                (
                    "resultado",
                    models.FileField(blank=True, upload_to="desafio/%Y/%m/%d/"),
                ),
            ],
        ),
    ]
