# Generated by Django 3.1.7 on 2021-04-19 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_auto_20210418_2057"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="edicao_olimpiada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.olimpimat",
            ),
        ),
        migrations.AddField(
            model_name="olimpimat",
            name="imagem",
            field=models.ImageField(default=0, upload_to="desafio/%Y/%m/%d/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="olimpimat",
            name="cronograma",
            field=models.FileField(upload_to="desafio/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="olimpimat",
            name="regulamento",
            field=models.FileField(upload_to="desafio/%Y/%m/%d/"),
        ),
    ]
