# Generated by Django 3.1.7 on 2021-04-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_auto_20210418_2100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="url_cadastro",
            field=models.URLField(blank=True),
        ),
    ]
