# Generated by Django 3.0.7 on 2021-02-16 23:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name given to function / role / position",
                        max_length=100,
                        unique=True,
                        verbose_name="nome",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        help_text="Hierarchical value of function / role / position",
                        verbose_name="value",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="role creation date",
                        verbose_name="created in",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="primeiro nome"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="último nome"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        error_messages={
                            "unique": "A user with that email address already exists."
                        },
                        max_length=254,
                        unique=True,
                        verbose_name="endereço de email",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Indica que usuário consegue acessar este site de administração.",
                        verbose_name="membro da equipe",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica que o usuário será tratado como ativo. Ao invés de excluir contas de usuário, desmarque isso.",
                        verbose_name="ativo",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="User registration date",
                        verbose_name="data de registro",
                    ),
                ),
                (
                    "soft_delet",
                    models.DateTimeField(
                        blank=True,
                        help_text="exclusion data the user if he has been excluded",
                        null=True,
                        verbose_name="deleted",
                    ),
                ),
                (
                    "is_trusty",
                    models.DateTimeField(
                        blank=True,
                        help_text="date the user was verified",
                        null=True,
                        verbose_name="is trusty",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        help_text="Individual registration",
                        max_length=15,
                        unique=True,
                        verbose_name="Individual registration",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="User address",
                        max_length=100,
                        verbose_name="address",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="user's phone number",
                        max_length=15,
                        verbose_name="phone Number",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="brief description about the user",
                        verbose_name="description",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="user position / function / role",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.Role",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuário",
                "verbose_name_plural": "usuários",
            },
            managers=[
                ("objects", user.models.UserManager()),
            ],
        ),
    ]
