# Generated by Django 3.1.6 on 2021-02-16 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="created",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, verbose_name="created in"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="nome"),
        ),
        migrations.AlterField(
            model_name="role",
            name="value",
            field=models.IntegerField(verbose_name="value"),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=100, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="soft_delet",
            field=models.DateTimeField(blank=True, null=True, verbose_name="deleted"),
        ),
    ]
