# Generated by Django 3.1.6 on 2021-03-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='processed_description',
            field=models.TextField(blank=True, help_text='brief processed description about the user', verbose_name='description'),
        ),
    ]
