# Generated by Django 3.1.6 on 2021-02-16 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210215_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='creted',
            new_name='created',
        ),
    ]
