# Generated by Django 3.1.6 on 2021-03-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_processed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/', verbose_name='Avatar'),
        ),
    ]
