# Generated by Django 3.1.7 on 2021-03-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_auto_20210301_2219"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cidade",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="uf",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
